apiVersion: apps/v1
kind: Deployment
metadata:
  name: tropinha-news
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tropinha-news
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: tropinha-news
        version: v1
    spec:
      containers:
        # IMAGE:TAG will be replaced by kustomize
        # during CI to make sure it matches the
        # build image and tag
        - image: IMAGE:TAG
          imagePullPolicy: IfNotPresent
          name: tropinha-news
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "5000"
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tropinha-news-secrets
                  key: telegram_token
            - name: TROPINHA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tropinha-news-secrets
                  key: tropinha_token
            - name: CLIMATE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tropinha-news-secrets
                  key: climate_token
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: tropinha-news-secrets
                  key: api_url
          resources:
            limits:
              cpu: 128m
              memory: 128Mi
            requests:
              cpu: 64m
              memory: 64Mi
